/* Independent fixed endings: calculation, transfer and a reasoned decision. */
(() => {
    const n = (prompt, expected, why, unit) => ({prompt, expected, type: 'number', why, unit});
    const c = (prompt, choices, expected, why) => ({prompt, choices, expected: String(expected), type: 'choice', why});
    const sets = {
        placeValue: [n('The value of the 4 in 3.045 is', .04, 'The 4 is in the hundredths place.'), n('Six million and fifty, written in figures, is', 6000050, 'Keep the empty thousands and hundreds places.'), n('A distance of 2 m and 7 hundredths of a metre is', 2.07, 'Seven hundredths is 0.07 m.', 'm'), c('Writing 0.80 instead of 0.8 leaves the value unchanged because', ['the zero adds no hundredths', 'zeros never affect a number', 'eight tenths means eight hundredths'], 0, 'Eight tenths and eighty hundredths represent the same amount.')],
        orderingNumbers: [n('The smallest of −0.7, −0.07 and 0 is', -.7, 'The smallest is furthest left on the number line.'), n('The greatest of 3.09, 3.9 and 3.099 is', 3.9, 'Compare 3.090, 3.900 and 3.099.'), n('Temperatures of −5 °C, 2 °C and −2 °C, in ascending order, have middle value', -2, 'Ascending order is from coldest to warmest.', '°C'), c('The number 4.08 is smaller than 4.8 because', ['it has more digits', 'it has fewer tenths', 'hundredths are larger than tenths'], 1, 'Their whole-number parts agree. Compare 0 tenths with 8 tenths.')],
        inequalitySymbols: [n('The greatest integer satisfying n < 6 is', 5, 'The strict inequality excludes six.'), n('The smallest integer satisfying −3 ≤ n < 2 is', -3, 'The left boundary allows equality.'), n('The number of integers satisfying 0 < n ≤ 4 is', 4, 'List 1, 2, 3 and 4.'), c('A rule allowing at most 8 people is written as', ['n < 8', 'n ≤ 8', 'n ≥ 8'], 1, 'At most allows eight and every smaller permitted count.')],
        powersOfTen: [n('0.48 × 1,000 =', 480, 'Every digit becomes a thousand times as large.'), n('62 ÷ 100 =', .62, 'Each digit moves two places right in the columns.'), n('There are this many 0.1-litre portions in 3 litres:', 30, 'Each litre has ten tenths.'), c('Dividing a positive number by 0.01 makes it', ['a hundred times as large', 'a hundred times as small', 'ten times as large'], 0, 'Division counts how many hundredths fit in the number.')],
        columnAddition: [n('3,768 + 2,457 =', 6225, 'Add from the ones, including each carried amount.'), n('8.06 + 2.7 =', 10.76, 'Write 2.70 below 8.06.'), n('Three lengths of 1.85 m, 0.95 m and 2.4 m total', 5.2, 'Align all three decimal points.', 'm'), c('A column total of 23 tenths is recorded as', ['23 in the tenths column', '3 tenths and 2 carried ones', '2 tenths and 3 carried ones'], 1, 'Twenty tenths make two ones; three tenths remain.')],
        columnSubtraction: [n('753 − 286 =', 467, 'Keep both halves of each exchange.'), n('15.8 − 7.46 =', 8.34, 'Write 15.80 first.'), n('A 6.75 m rope is 2.9 m longer than another rope. The shorter rope is', 3.85, 'Subtract 2.90 from 6.75.', 'm'), c('Exchanging a ten for ten ones', ['increases the number by ten', 'leaves the number unchanged', 'decreases the number by one'], 1, 'The value is renamed, not added or taken away.')],
        exchangingAcrossZeros: [n('4,000 − 658 =', 3342, 'Exchange from the thousands through the hundreds and tens.'), n('6.02 − 1.875 =', 4.145, 'Write 6.020, then record each exchange.'), n('Change from £20 for a £13.76 purchase is £', 6.24, 'Use 20.00 − 13.76.'), c('When an exchange passes through an empty column, that column keeps', ['10 units of its place', '9 units of its place', '0 units of its place'], 1, 'It receives ten and passes one to the next smaller place.')],
        longMultiplication: [n('246 × 37 =', 9102, 'Add the row for 7 and the row for 30.'), n('123 × 204 =', 25092, 'Combine the products for 200 and 4; there are no tens in 204.'), n('A hall has 28 rows of 36 seats. Its total number of seats is', 1008, 'Multiply the seats per row by the number of rows.'), c('The second row of 246 × 37 ends in a zero because it represents', ['246 × 3', '246 × 30', '246 + 30'], 1, 'The 3 in 37 counts tens.')],
        multiplyingDecimals: [n('1.8 × 2.4 =', 4.32, '18 × 24 = 432; divide the product by 100.'), n('0.06 × 0.5 =', .03, 'The integer product 30 needs three decimal places.'), n('A rectangle 1.2 m long and 0.8 m wide has area', .96, 'Multiply its two lengths.', 'm²'), c('For 0.5 × 0.4, the integer product 20 becomes', ['0.02', '0.20', '2.0'], 1, 'There are two decimal places across the two factors.')],
        shortDivision: [n('816 ÷ 4 =', 204, 'Keep the zero tens in the answer.'), n('22.5 ÷ 6 =', 3.75, 'Continue the division into hundredths.'), n('Sharing 7 m equally into 8 pieces gives a piece length of', .875, 'Divide 7.000 by 8.', 'm'), c('In 936 ÷ 4, one hundred remains after the first step. With the 3 tens, it becomes', ['13 tens', '4 tens', '103 tens'], 0, 'Rename the hundred as ten tens, then add three tens.')],
        interpretingRemainders: [n('Packing 47 eggs into boxes holding 6 fills this many complete boxes:', 7, 'Seven complete boxes use 42 eggs.'), n('Packing every egg needs this many boxes:', 8, 'The five remaining eggs need another box.'), n('Sharing 37 litres equally between 8 containers puts in each container', 4.625, 'Share the remaining five litres too; continue into decimal places.', 'litres'), c('For 25 people travelling in cars holding 4 passengers each, the number of cars is', ['6, because the decimal is below halfway', '7, because every passenger needs a seat', '6.25, because that is the exact quotient'], 1, 'A partly filled car is still a whole car.')],
        longDivision: [n('2,448 ÷ 24 =', 102, 'Do not omit the zero in the tens column.'), n('45.6 ÷ 16 =', 2.85, 'Continue into hundredths, then check by multiplying by 16.'), n('Each box holds 24 bolts. Packing all 145 bolts needs', 7, 'Six boxes hold 144 bolts. The last bolt needs another box.', 'boxes'), c('At each long-division step, the multiple subtracted is', ['the nearest multiple, even if larger', 'the largest multiple not exceeding the current amount', 'always ten times the divisor'], 1, 'The remainder must be non-negative and smaller than the divisor.')],
        dividingByDecimals: [n('7.2 ÷ 0.3 =', 24, 'Scale both numbers by ten.'), n('0.84 ÷ 0.07 =', 12, 'Scale both numbers by a hundred.'), n('The number of 0.45 m lengths in 5.4 m is', 12, 'Calculate 540 ÷ 45.'), c('Multiplying both dividend and divisor by 100', ['multiplies the quotient by 100', 'leaves the quotient unchanged', 'divides the quotient by 100'], 1, 'The same number of proportionally larger groups still fits.')],
        usingAGivenCalculation: [n('Given 37 × 24 = 888, the value of 3.7 × 2.4 is', 8.88, 'Both factors are divided by ten.'), n('Using the same fact, 88.8 ÷ 2.4 =', 37, 'The product and divisor are both a tenth of the original values.'), n('At £2.40 each, 37 tickets cost £', 88.8, '24 × 37 = 888, then divide the product by ten.'), c('Compared with 37 × 24, the product 370 × 2.4 is', ['unchanged', 'ten times larger', 'ten times smaller'], 0, 'One factor is ten times larger and the other ten times smaller.')]
    };
    const normalise = value => {
        const raw = String(value).trim().replace(/−/g, '-');
        return /^[+-]?\d{1,3}(?:,\d{3})+(?:\.\d*)?$/.test(raw) ? raw.replace(/,/g, '') : raw;
    };
    window.WrittenMethodsRecallBank = {
        build: page => sets[page] || [],
        correct(q, value) {
            const raw = normalise(value);
            return q.type === 'choice' ? raw === q.expected : /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw) && Number(raw) === q.expected;
        },
        help(q, value) {
            return (q.type === 'choice' ? '“' + q.choices[Number(value)] + '” does not fit. ' : 'Check your entry, ' + value + '. ') + q.why;
        }
    };
})();
